#!/bin/sh

CMD="python3 bdf_to_header.py --name"

${CMD} GENERA_BIG
${CMD} GENERA_BIG_B
${CMD} HELVETICA_8
${CMD} HELVETICA_10
${CMD} HELVETICA_10_B
${CMD} HELVETICA_12
${CMD} HELVETICA_14
${CMD} HELVETICA_18
${CMD} HELVETICA_18_B
${CMD} HL_18
${CMD} HL_18_B
${CMD} SWISS_20
${CMD} SWISS_20_B
